#!/usr/bin/env python3
"""Render the harness scratch-address table from ``HARNESS_SCRATCH``.

``docs/memory_safety.md`` used to carry the table as hand-maintained
markdown, and it drifted from the code three ways (issue #169).  The
table is now *generated* from ``c64_test_harness.memory_policy
.HARNESS_SCRATCH`` and the doc carries it between marker comments;
``tests/test_memory_table_doc.py`` fails the suite when they differ.

Usage::

    scripts/gen_memory_table.py            # print the markdown table
    scripts/gen_memory_table.py --summary  # one-line summary for briefs
    scripts/gen_memory_table.py --check    # exit 1 if the doc has drifted
    scripts/gen_memory_table.py --write    # rewrite the doc's block

The script imports from this checkout's ``src/`` (not the installed
package) so the table always reflects the code next to it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO / "src"))

from c64_test_harness.memory_policy import HARNESS_SCRATCH, ScratchRegion  # noqa: E402

DOC_PATH = _REPO / "docs" / "memory_safety.md"
BEGIN = "<!-- BEGIN HARNESS_SCRATCH TABLE (generated by scripts/gen_memory_table.py — do not edit by hand) -->"
END = "<!-- END HARNESS_SCRATCH TABLE -->"


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_table(regions: tuple[ScratchRegion, ...] = HARNESS_SCRATCH) -> str:
    """Return the markdown table (no trailing newline)."""
    lines = [
        "| Address(es) | Bytes | Owner | Purpose | Configurable |",
        "|---|---:|---|---|---|",
    ]
    any_transient = False
    for r in regions:
        span = f"`{r.span}`"
        if r.transient:
            span += " †"
            any_transient = True
        owner = ", ".join(f"`{o.strip()}`" for o in r.owner.split(","))
        lines.append(
            f"| {span} | {r.length} | {_md_cell(owner)} | "
            f"{_md_cell(r.purpose)} | {_md_cell(r.configurable)} |"
        )
    if any_transient:
        lines.append("")
        lines.append(
            "† *transient* — the prior contents are written back afterwards "
            "(best-effort for the liveness probe: only on success). It does "
            "NOT mean the span is safe to execute from while the operation "
            "runs: the REU window is filled by REC DMA with the CPU live and "
            "`MemoryPolicy` cannot see that fill; `extract_reu_contents` "
            "warns when the transport's policy declares RAM inside it. "
            "Declared like every other write, but not withheld by "
            "`MemoryArbiter` by default."
        )
    return "\n".join(lines)


def render_summary(regions: tuple[ScratchRegion, ...] = HARNESS_SCRATCH) -> str:
    """One-line summary of the non-transient spans, for CLAUDE.md-style briefs."""
    spans = [f"`{r.span}`" for r in regions if not r.transient]
    return ", ".join(spans)


def render_block(regions: tuple[ScratchRegion, ...] = HARNESS_SCRATCH) -> str:
    return f"{BEGIN}\n{render_table(regions)}\n{END}"


def extract_block(doc_text: str) -> str | None:
    """Return the marker-delimited block from *doc_text*, or None if absent."""
    start = doc_text.find(BEGIN)
    end = doc_text.find(END)
    if start < 0 or end < 0 or end < start:
        return None
    return doc_text[start : end + len(END)]


def replace_block(doc_text: str, block: str) -> str:
    current = extract_block(doc_text)
    if current is None:
        raise ValueError(f"{DOC_PATH} has no HARNESS_SCRATCH markers")
    return doc_text.replace(current, block, 1)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--summary", action="store_true", help="print the one-line summary")
    mode.add_argument("--check", action="store_true", help="exit 1 if the doc block differs")
    mode.add_argument("--write", action="store_true", help="rewrite the doc block in place")
    args = ap.parse_args(argv)

    if args.summary:
        print(render_summary())
        return 0
    if args.check or args.write:
        text = DOC_PATH.read_text(encoding="utf-8")
        expected = render_block()
        current = extract_block(text)
        if current == expected:
            print(f"{DOC_PATH.relative_to(_REPO)}: table is up to date")
            return 0
        if args.write:
            DOC_PATH.write_text(replace_block(text, expected), encoding="utf-8")
            print(f"{DOC_PATH.relative_to(_REPO)}: table rewritten")
            return 0
        print(
            f"{DOC_PATH.relative_to(_REPO)}: HARNESS_SCRATCH table has drifted "
            f"from the code — run scripts/gen_memory_table.py --write",
            file=sys.stderr,
        )
        return 1
    print(render_table())
    return 0


if __name__ == "__main__":
    sys.exit(main())
